db.userList.insertMany([
    { userid: "hjk", status: "C", age: 33      },
    { user_id: "user_abc", status: "A", age: 25 },
    { user_id: "user_def", status: "B", age: 30 },
    { user_id: "user_ghi", status: "C", age: 22 },
    { user_id: "user_jkl", status: "D", age: 28 },
    { user_id: "user_mno", status: "A", age: 55 },
    { user_id: "user_pqr", status: "B", age: 40 },
    { user_id: "user_stu", status: "C", age: 26 },
    { user_id: "user_vwx", status: "D", age: 32 },
    { user_id: "user_yza", status: "A", age: 24 },
    { user_id: "user_bcd", status: "B", age: 50},
    { user_id: "user_efg", status: "C", age: 58 },
    { user_id: "user_hij", status: "D", age: 33 },
    { user_id: "user_klm", status: "A", age: 31 },
    { user_id: "user_nop", status: "B", age: 23 },
    { user_id: "user_qrs", status: "C", age: 34 },
    { user_id: "user_tuv", status: "D", age: 21 },
    { user_id: "user_wxy", status: "A", age: 38 },
    { user_id: "user_zab", status: "B", age: 63 },
    { user_id: "user_cde", status: "C", age: 39 },
    { user_id: "user_fgh", status: "D", age: 20 },
  ]);